FROM ubuntu:22.04
COPY . /distr
RUN apt update && \
	apt -y install /distr/wkhtmltox_0.12.6.1-2.jammy_amd64.deb python3 pip
RUN pip install pyproj pyshp pyyaml pillow pypdf2 pdfkit cherrypy untangle \
	jinja2 requests
RUN cp -r /distr/PT_Serif /usr/share/fonts/truetype && fc-cache -f -v